//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dddd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string article { get; set; }
        public string title { get; set; }
        public string unit { get; set; }
        public double cost { get; set; }
        public double maxDiscount { get; set; }
        public int manufacturerId { get; set; }
        public int providerId { get; set; }
        public int categoryId { get; set; }
        public double currentDiscount { get; set; }
        public double discounedPrice { get; set; }
        public int count_in_storage { get; set; }
        public string description { get; set; }
        public string photo { get; set; }
        public int productId { get; set; }
        
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
